#!/usr/bin/env bash
# Requirements:
#install nginx on your webserver, configure nginx to run on port 80.

apt -y update
apt -y install ngnix

ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start



