#!/usr/bin/env bash
# Requirements:
#install nginx on your webserver, configure nginx to run on port 80.

sudo apt update
sudo apt install ngnix

ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx restart



