#!/usr/bin/env bash

# Script that configures SSH key-based authentication

# Define SSH config file
SSH_CONFIG_FILE=~/.ssh/config

# Check if the SSH config file exists, if not create it
if [ ! -f "$SSH_CONFIG_FILE" ]; then
    touch "$SSH_CONFIG_FILE"
fi

# Add SSH config
echo "Host web-01" >> "$SSH_CONFIG_FILE"
echo "    Hostname 35.153.232.54" >> "$SSH_CONFIG_FILE"
echo "    User ubuntu" >> "$SSH_CONFIG_FILE"
echo "    IdentityFile ~/.ssh/school" >> "$SSH_CONFIG_FILE"
echo "    PasswordAuthentication no" >> "$SSH_CONFIG_FILE"

# Success message
echo "SSH configuration for web-01 has been added to $SSH_CONFIG_FILE"

ssh -v web-01
